spring.application.name: eureka-server
server.port: 9001
eureka.instance.hostname: localhost
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

eureka.server.enable-self-preservation: false
#实例名称显示ip
eureka.instance.preferIpAddress: true